### PR TITLE
fix for use with git submodules

### PR DESCRIPTION
**Pull request by FreddyFunk**
This PR solves conflicts when using this repo as a git submodule. This simplifies using this repo within large git projects.

### CODE REVIEW

**Comment by fogti** [comment]
I think the main function should then be made conditional using preprocessor macros.

**Comment by FreddyFunk** [comment]
Addressed feedback from @zserik . 

Both commits might not be the most ideal solution. 
For the use of this thread pool only the `ThreadPool.h` file is nessesary while the `example.cpp` file is intended to be a show case for an example code. Therefore it would be the best solution integrated this example code into the `README.md` and remove the `example.cpp` file from the code base completly.
Let me know what you think about this suggestion. I can quickly update this pull request to fullfil this suggestion if it gets approved.

**Comment by fogti** [comment]
Ok, the solution to delete the example.cxx and put the content into README sounds good, especially because the example.cxx is so small.

**Comment by FreddyFunk** [comment]
Done

**Comment by fogti** [comment]
ok

**Pull request closed without merging**
