### PR TITLE
add CMakeLists.txt

### PR DESCRIPTION
**Pull request by Smalldy**
A simple cmake file for c++11

### CODE REVIEW

**Comment by c02y** [comment]
It is always better to clean all the blank lines at the end of file.

And I don't think the author would accept this kind of CMakeLists.txt, since this repo is simply just a .h file and a cpp demo file.

**Comment by Smalldy** [comment]
yes it's my mistake




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月12日(星期六) 晚上9:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [progschj/ThreadPool] add CMakeLists.txt (PR #95)





 
It is always better to clean all the blank lines at the end of file.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Smalldy** [comment]
> 

maybe you are right , I just want to make it easy to run ...

**Comment by c02y** [comment]
> > 
> 
> maybe you are right , I just want to make it easy to run ...

You can just type once and then use something like `Ctrl-r` for your shell to reuse the command from the shell history.

**Comment by Smalldy** [comment]
> > > 
> > 
> > 
> > maybe you are right , I just want to make it easy to run ...
> 
> You can just type once and then use something like `Ctrl-r` for your shell to reuse the command from the shell history.

So sad that the last update was 8 years ago.. It is unnecessary to talk about the detail now.  : (

**Comment by Qix-** [comment]
```cmake
cmake_minimum_required (VERSION 3.2)
project (threadpool)

add_library (ThreadPool INTERFACE)
target_include_directories (ThreadPool INTERFACE "${CMAKE_CURRENT_SOURCE_DIR}")
target_compile_features (ThreadPool INTERFACE cxx_std_11)

if (BUILD_TESTING)
    enable_testing ()
    add_executable (test-ThreadPool example.cpp)
    target_link_libraries (test-ThreadPool PRIVATE ThreadPool)
    add_test (NAME ThreadPool-test COMMAND $<TARGET_FILE:test-ThreadPool>)
endif ()
```

This is more of a complete CMake file for this project FWIW.

**Pull request closed without merging**
